# Generated by Django 3.2.5 on 2021-07-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_remove_animal_characteristics'),
        ('characteristic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='animals',
            field=models.ManyToManyField(to='animal.Animal'),
        ),
    ]
