# Generated by Django 3.2.5 on 2021-07-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_remove_animal_characteristics'),
        ('characteristic', '0002_characteristic_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='animals',
            field=models.ManyToManyField(related_name='animals', to='animal.Animal'),
        ),
    ]
