# Generated by Django 3.2.5 on 2021-07-29 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('animal', '0002_rename_group_id_animal_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='group.group'),
        ),
    ]
