# Generated by Django 3.2.5 on 2021-07-31 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_alter_animal_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='characteristics',
        ),
    ]
